import Tasks from "@/component/task"
export default function Home() {
  
  return (
    <div className="">
      <h1 className="text-8xl text-center">Task list</h1>
      <Tasks/>
      <footer className="bg-[#2c3e50] text-2xl mt-[470px] rounded-2xl p-4 font-mono text-[wheat]">This project generated by M.afroozi | special thanks to master Ghorbanian❤️</footer>
    </div>
  )
}